version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "${DOCKER_PORT}:${PORT}"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data: